import type {
  ErrorRecord,
  KnowledgeDoc,
  MarketItem,
  McpTool,
  ServiceItem,
  Workspace,
} from "./types";

export const workspaces: Workspace[] = [
  { id: "prod", name: "生产工作区", environment: "生产集群 · 华北双活", color: "#6c5ce7" },
  { id: "sandbox", name: "研发沙盒", environment: "开发集群 · 隔离网络", color: "#0ea5e9" },
  { id: "external", name: "外部接入区", environment: "第三方网关 · 受控访问", color: "#f59e0b" },
];

export const services: ServiceItem[] = [
  {
    id: "chart",
    name: "图表生成",
    code: "CHART-SERVICE",
    summary: "将结构化业务数据转化为可用于汇报、分析和运营看板的图表资产。",
    businessLine: "数据智能",
    department: "智能产品部",
    status: "需要关注",
    workspaceIds: ["prod", "sandbox"],
    owner: "林晓",
    productOwner: "陈希",
    techOwner: "高远",
    updatedAt: "今天 09:42",
  },
  {
    id: "document",
    name: "文档处理",
    code: "DOC-SERVICE",
    summary: "统一处理 PDF、Office、网页与协作文档的解析、摘要和同步任务。",
    businessLine: "企业效率",
    department: "协同平台部",
    status: "运行正常",
    workspaceIds: ["prod", "sandbox", "external"],
    owner: "王晨",
    productOwner: "周可",
    techOwner: "孙睿",
    updatedAt: "昨天 16:20",
  },
  {
    id: "search",
    name: "企业搜索",
    code: "SEARCH-SERVICE",
    summary: "连接企业知识、人员目录与业务数据库，为 AI 提供可信检索能力。",
    businessLine: "知识智能",
    department: "AI 平台部",
    status: "维护中",
    workspaceIds: ["prod", "sandbox"],
    owner: "赵一",
    productOwner: "郑航",
    techOwner: "许宁",
    updatedAt: "3 天前",
  },
  {
    id: "collaboration",
    name: "协同办公",
    code: "COLLAB-SERVICE",
    summary: "连接 Jira、Linear、Slack 等协作系统，帮助 AI 执行跨系统工作流。",
    businessLine: "企业效率",
    department: "协同平台部",
    status: "运行正常",
    workspaceIds: ["prod", "external"],
    owner: "陈宇",
    productOwner: "刘佳",
    techOwner: "唐森",
    updatedAt: "5 天前",
  },
];

const schemaInput = `{
  "type": "object",
  "required": ["data", "title"],
  "properties": {
    "data": { "type": "array", "description": "图表数据" },
    "title": { "type": "string", "maxLength": 80 },
    "theme": { "enum": ["light", "dark", "brand"] }
  }
}`;

const schemaOutput = `{
  "type": "object",
  "properties": {
    "assetUrl": { "type": "string", "format": "uri" },
    "width": { "type": "integer" },
    "height": { "type": "integer" },
    "altText": { "type": "string" }
  }
}`;

export const mcps: McpTool[] = [
  {
    id: "bar-chart",
    name: "generate_bar_chart",
    displayName: "条形图生成",
    serviceId: "chart",
    workspaceIds: ["prod", "sandbox"],
    status: "已上架",
    version: "v2.4.1",
    calls: 24891,
    successRate: 99.2,
    avgTokens: 1248,
    latency: 820,
    errorRate: 0.8,
    score: 94,
    updatedAt: "今天 09:42",
    description:
      "当用户需要比较多个类别、展示排名或观察横向差异时，生成清晰的条形图。不要用于时间趋势或占比总和展示。",
    owners: { product: "陈希", developer: "高远", ops: "林晓" },
    clients: ["ChatGPT Enterprise", "Claude Desktop", "内部 Copilot"],
    authMode: "平台 OpenAPI",
    transport: "Streamable HTTP",
    workflowName: "chart.generate_bar",
    infraName: "企业图表 · 条形图",
    inputSchema: schemaInput,
    outputSchema: schemaOutput,
  },
  {
    id: "pie-chart",
    name: "generate_pie_chart",
    displayName: "饼状图生成",
    serviceId: "chart",
    workspaceIds: ["prod", "sandbox"],
    status: "已上架",
    version: "v1.9.0",
    calls: 8210,
    successRate: 99.6,
    avgTokens: 998,
    latency: 710,
    errorRate: 0.4,
    score: 91,
    updatedAt: "5 天前",
    description: "将不超过八个分类的占比数据转换为饼状图，并生成无障碍替代文本。",
    owners: { product: "陈希", developer: "何川", ops: "林晓" },
    clients: ["ChatGPT Enterprise", "内部 Copilot"],
    authMode: "平台 OpenAPI",
    transport: "Streamable HTTP",
    workflowName: "chart.generate_pie",
    infraName: "企业图表 · 饼状图",
    inputSchema: schemaInput,
    outputSchema: schemaOutput,
  },
  {
    id: "line-chart",
    name: "generate_line_chart",
    displayName: "折线图生成",
    serviceId: "chart",
    workspaceIds: ["prod", "sandbox"],
    status: "灰度中",
    version: "v3.0.0-rc2",
    calls: 6240,
    successRate: 97.8,
    avgTokens: 1384,
    latency: 940,
    errorRate: 2.2,
    score: 86,
    updatedAt: "今天 08:15",
    description: "用于展示连续时间维度下的趋势、波动与多序列对比。",
    owners: { product: "陈希", developer: "周扬", ops: "林晓" },
    clients: ["内部 Copilot"],
    authMode: "平台 OpenAPI",
    transport: "SSE",
    workflowName: "chart.generate_line",
    infraName: "企业图表 · 趋势图",
    inputSchema: schemaInput,
    outputSchema: schemaOutput,
  },
  {
    id: "document-parse",
    name: "parse_document",
    displayName: "文档解析",
    serviceId: "document",
    workspaceIds: ["prod", "sandbox", "external"],
    status: "已上架",
    version: "v4.6.2",
    calls: 19402,
    successRate: 98.7,
    avgTokens: 2106,
    latency: 1240,
    errorRate: 1.3,
    score: 88,
    updatedAt: "昨天 16:20",
    description: "解析 PDF、Word、Excel 和网页，返回章节结构、正文、表格及来源定位信息。",
    owners: { product: "周可", developer: "孙睿", ops: "王晨" },
    clients: ["ChatGPT Enterprise", "Claude Desktop", "Cursor", "内部 Copilot"],
    authMode: "无需鉴权",
    transport: "Streamable HTTP",
    workflowName: "document.parse",
    infraName: "文档理解 · 内容解析",
    inputSchema: schemaInput,
    outputSchema: schemaOutput,
  },
  {
    id: "notion-sync",
    name: "sync_notion_page",
    displayName: "Notion 页面同步",
    serviceId: "document",
    workspaceIds: ["sandbox", "external"],
    status: "测试中",
    version: "v0.8.3",
    calls: 4608,
    successRate: 94.8,
    avgTokens: 1876,
    latency: 1820,
    errorRate: 5.2,
    score: 72,
    updatedAt: "8 天前",
    description: "同步 Notion 页面内容到企业知识库。当前描述未明确数据库权限和增量同步限制。",
    owners: { product: "周可", developer: "孙睿", ops: "王晨" },
    clients: ["Claude Desktop", "内部 Copilot"],
    authMode: "用户 OAuth 2.0",
    transport: "SSE",
    workflowName: "notion.sync_page",
    infraName: "知识同步 · Notion",
    inputSchema: schemaInput,
    outputSchema: schemaOutput,
  },
  {
    id: "knowledge-search",
    name: "search_enterprise_knowledge",
    displayName: "企业知识搜索",
    serviceId: "search",
    workspaceIds: ["prod", "sandbox"],
    status: "维护中",
    version: "v2.1.7",
    calls: 16805,
    successRate: 96.1,
    avgTokens: 876,
    latency: 640,
    errorRate: 3.9,
    score: 76,
    updatedAt: "3 天前",
    description: "在企业知识库中检索与用户问题相关的内容，并返回可追溯的来源片段。",
    owners: { product: "郑航", developer: "许宁", ops: "赵一" },
    clients: ["ChatGPT Enterprise", "内部 Copilot"],
    authMode: "用户密钥",
    transport: "Streamable HTTP",
    workflowName: "knowledge.search",
    infraName: "企业检索 · 知识搜索",
    inputSchema: schemaInput,
    outputSchema: schemaOutput,
  },
  {
    id: "employee-search",
    name: "search_employee",
    displayName: "员工目录搜索",
    serviceId: "search",
    workspaceIds: ["prod"],
    status: "已上架",
    version: "v1.4.0",
    calls: 7320,
    successRate: 99.1,
    avgTokens: 420,
    latency: 380,
    errorRate: 0.9,
    score: 92,
    updatedAt: "2 天前",
    description: "根据姓名、部门、技能或办公地点检索员工公开目录信息。",
    owners: { product: "郑航", developer: "许宁", ops: "赵一" },
    clients: ["内部 Copilot"],
    authMode: "平台 OpenAPI",
    transport: "Streamable HTTP",
    workflowName: "employee.search",
    infraName: "组织服务 · 员工查询",
    inputSchema: schemaInput,
    outputSchema: schemaOutput,
  },
  {
    id: "jira-create",
    name: "create_jira_issue",
    displayName: "Jira 工单创建",
    serviceId: "collaboration",
    workspaceIds: ["prod", "external"],
    status: "已上架",
    version: "v2.0.4",
    calls: 2918,
    successRate: 99.1,
    avgTokens: 642,
    latency: 920,
    errorRate: 0.9,
    score: 90,
    updatedAt: "5 天前",
    description: "在获得用户确认后创建 Jira 工单，支持项目、类型、优先级和经办人字段。",
    owners: { product: "刘佳", developer: "唐森", ops: "陈宇" },
    clients: ["ChatGPT Enterprise", "Claude Desktop"],
    authMode: "用户 OAuth 2.0",
    transport: "Streamable HTTP",
    workflowName: "jira.issue.create",
    infraName: "研发协作 · 创建工单",
    inputSchema: schemaInput,
    outputSchema: schemaOutput,
  },
];

export const errorRecords: ErrorRecord[] = [
  {
    id: "err-401-notion",
    mcpId: "notion-sync",
    code: "MCP-AUTH-401",
    category: "鉴权失败",
    message: "Notion OAuth 访问令牌已失效",
    count: 138,
    firstAt: "2026-07-20 08:12:31",
    lastAt: "2026-07-22 14:26:08",
    resolveMinutes: 126,
    severity: "P1",
    status: "处理中",
    impact: "同步任务终止，AI 无法引用用户刚刚更新的 Notion 页面。",
    userMessage: "把项目复盘页面同步到团队知识库。",
    llmMessage: "我会先读取页面并执行增量同步，完成后返回同步摘要。",
    toolInput: `{"page_id":"8af1...","mode":"incremental","include_children":true}`,
    toolOutput: `{"error":"invalid_token","status":401,"retryable":false}`,
    summary: "授权过期使 AI 的知识同步承诺未能兑现，用户需要重新授权后重试。",
  },
  {
    id: "err-timeout-line",
    mcpId: "line-chart",
    code: "MCP-TIMEOUT-504",
    category: "服务超时",
    message: "图表渲染任务超过 3 秒网关限制",
    count: 92,
    firstAt: "2026-07-21 10:06:12",
    lastAt: "2026-07-22 13:59:40",
    resolveMinutes: 48,
    severity: "P1",
    status: "待处理",
    impact: "AI 已完成数据分析，但未能返回可视化图片。",
    userMessage: "画出过去 12 个月三个产品线的收入趋势。",
    llmMessage: "我将生成一张多序列折线图，并标注增长拐点。",
    toolInput: `{"series":3,"points":36,"theme":"brand","annotations":true}`,
    toolOutput: `{"error":"gateway_timeout","status":504,"elapsed_ms":3002}`,
    summary: "渲染超时导致 AI 只能返回文字结论，关键趋势缺少预期的图表佐证。",
  },
  {
    id: "err-schema-search",
    mcpId: "knowledge-search",
    code: "MCP-SCHEMA-422",
    category: "响应格式错误",
    message: "引用来源缺少必填字段 source_url",
    count: 76,
    firstAt: "2026-07-19 17:42:04",
    lastAt: "2026-07-22 11:08:22",
    resolveMinutes: 210,
    severity: "P2",
    status: "处理中",
    impact: "AI 返回了答案，但无法展示可点击的知识来源。",
    userMessage: "公司对于客户数据导出的审批要求是什么？",
    llmMessage: "我会检索最新的数据安全制度，并给出来源。",
    toolInput: `{"query":"客户数据导出 审批要求","top_k":5}`,
    toolOutput: `{"results":[{"title":"数据安全制度","source_url":null}]}`,
    summary: "搜索结果可用但引用链断裂，降低了 AI 回答的可信度和审计能力。",
  },
];

export const marketItems: MarketItem[] = [
  {
    id: "figma",
    name: "Figma MCP",
    provider: "Figma, Inc.",
    category: "设计协作",
    summary: "读取设计文件、组件变量和 Dev Mode 上下文，辅助设计到代码工作流。",
    protocol: "MCP · Streamable HTTP",
    auth: "用户 OAuth 2.0",
    llmSupport: "支持 ChatGPT、Claude、Cursor 等主流客户端",
    pricing: "使用现有 Figma 席位，企业可集中采购",
    visibility: "可隐藏服务方名称，仅展示内部工具名称",
    verified: true,
    installs: 1820,
    tags: ["官方", "OAuth", "设计"],
  },
  {
    id: "github",
    name: "GitHub MCP Server",
    provider: "GitHub",
    category: "研发工具",
    summary: "查询仓库、议题、拉取请求和 Actions，并支持受控写操作。",
    protocol: "MCP · stdio / HTTP",
    auth: "用户 OAuth 2.0 或 PAT",
    llmSupport: "全 LLM 支持",
    pricing: "开源免费，受 GitHub 账户权限限制",
    visibility: "服务方名称对用户可见",
    verified: true,
    installs: 5420,
    tags: ["官方", "开源", "研发"],
  },
  {
    id: "notion",
    name: "Notion Connector",
    provider: "Notion Labs",
    category: "知识管理",
    summary: "读取和维护页面、数据库及评论，适用于企业知识同步。",
    protocol: "OpenAPI 封装为 MCP",
    auth: "每位用户独立 OAuth 2.0",
    llmSupport: "支持具备远程 MCP 能力的客户端",
    pricing: "无需额外 MCP 费用，受 Notion 订阅限制",
    visibility: "可使用企业知识库品牌名替代",
    verified: true,
    installs: 3860,
    tags: ["知识库", "OAuth", "官方"],
  },
  {
    id: "postgres",
    name: "PostgreSQL Inspector",
    provider: "社区维护",
    category: "数据与分析",
    summary: "以只读方式检查数据库结构并执行受限制的查询。",
    protocol: "MCP · stdio",
    auth: "平台集中托管加密凭证",
    llmSupport: "支持本地 MCP 客户端",
    pricing: "开源免费",
    visibility: "必须隐藏真实数据库和供应商信息",
    verified: false,
    installs: 2310,
    tags: ["社区", "数据库", "高风险"],
  },
  {
    id: "sentry",
    name: "Sentry Observability",
    provider: "Functional Software, Inc.",
    category: "监控运维",
    summary: "查询错误事件、发布版本和性能追踪，辅助故障定位。",
    protocol: "MCP · Remote HTTP",
    auth: "组织级 OAuth 2.0",
    llmSupport: "部分 LLM 客户端",
    pricing: "复用企业 Sentry 套餐",
    visibility: "服务方名称可见",
    verified: true,
    installs: 990,
    tags: ["运维", "OAuth", "官方"],
  },
];

export const knowledgeDocs: KnowledgeDoc[] = [
  {
    id: "product-design",
    title: "MCP 产品设计规范",
    category: "产品开发手册",
    summary: "从 Service 边界、工具命名、描述设计到参数可理解性的完整产品规范。",
    owner: "陈希",
    version: "v2.3",
    updatedAt: "2026-07-18",
    readMinutes: 12,
    tags: ["产品", "工具描述", "命名"],
    sections: [
      {
        title: "先定义 Service，再定义工具",
        content:
          "Service 代表稳定的业务能力边界，MCP 工具代表可被模型独立选择和调用的原子动作。一个工具只解决一个明确问题，避免把查询、修改和审批混在同一工具中。",
      },
      {
        title: "工具描述必须回答四个问题",
        content:
          "描述要说明适合何时调用、需要什么上下文、会产生什么结果、哪些情况下不应该调用。不要只复述工具名称，也不要使用只有内部人员理解的缩写。",
      },
      {
        title: "参数设计",
        content:
          "参数名保持稳定、语义清晰；枚举值提供中文说明；高风险写操作必须有确认参数；所有时间字段明确时区；所有资源标识说明获取方式。",
      },
    ],
  },
  {
    id: "technical-guide",
    title: "企业 MCP Server 技术接入手册",
    category: "技术开发手册",
    summary: "覆盖 Transport、Schema、鉴权、日志、Trace、超时和健康检查。",
    owner: "高远",
    version: "v3.1",
    updatedAt: "2026-07-21",
    readMinutes: 18,
    tags: ["研发", "接入", "Transport"],
    sections: [
      {
        title: "Transport 选择",
        content:
          "生产服务优先使用 Streamable HTTP；需要持续推送的遗留服务可使用 SSE；本地开发工具可使用 stdio。所有远程服务必须提供健康检查端点。",
      },
      {
        title: "可观测性要求",
        content:
          "每次调用生成 trace_id，并记录客户端、模型、工具版本、描述版本、脱敏后的输入输出、耗时、Token 和错误码。日志不得包含明文凭证。",
      },
      {
        title: "错误契约",
        content:
          "错误返回必须包含稳定错误码、用户可理解的 message、是否可重试 retryable、建议等待时间和可选修复动作。禁止直接向模型暴露内部堆栈。",
      },
    ],
  },
  {
    id: "onboarding",
    title: "新 MCP 上架与灰度发布流程",
    category: "接入流程",
    summary: "从申请、技术评审、安全评审、沙盒验证到灰度和正式上架。",
    owner: "周可",
    version: "v1.8",
    updatedAt: "2026-07-16",
    readMinutes: 8,
    tags: ["流程", "上架", "审批"],
    sections: [
      {
        title: "准备材料",
        content:
          "提交 Service 归属、产品负责人、开发负责人、运维负责人、工具描述、输入输出 Schema、权限清单、测试用例和回滚方案。",
      },
      {
        title: "沙盒验证",
        content:
          "至少执行成功、参数缺失、权限不足、超时和依赖不可用五类用例，同时检查模型是否会在不合适的场景误调用。",
      },
      {
        title: "灰度策略",
        content:
          "先向内部测试用户开放，再按客户端或 Workspace 扩大范围。灰度期间重点监控首次调用成功率、重试率和用户撤销率。",
      },
    ],
  },
  {
    id: "incident",
    title: "MCP 服务异常运维处理流程",
    category: "运维处理流程",
    summary: "定义 P0-P3 事故分级、响应责任、止损、回滚和复盘要求。",
    owner: "林晓",
    version: "v2.0",
    updatedAt: "2026-07-22",
    readMinutes: 10,
    tags: ["运维", "事故", "回滚"],
    sections: [
      {
        title: "先判断影响，再定位根因",
        content:
          "确认受影响 Workspace、MCP、AI 客户端和用户数量。P0/P1 优先执行限流、降级或下线，恢复服务后再继续根因分析。",
      },
      {
        title: "上下文保全",
        content:
          "保留出错时的对话上下文、工具描述版本、调用参数、返回结果、前后置工具和模型信息，供产品、研发和运维共同判断影响。",
      },
      {
        title: "复盘要求",
        content:
          "复盘必须包含时间线、直接原因、系统性原因、监控缺口、修复动作、负责人和截止时间，并关联知识库和错误码。",
      },
    ],
  },
];

export const trendByRange: Record<string, number[]> = {
  "7": [2840, 3210, 3060, 3720, 3490, 4180, 4510],
  "15": [2100, 2460, 2380, 2820, 3010, 2870, 3220, 3540, 3310, 3780, 3650, 4010, 3920, 4380, 4510],
  "30": [
    1620, 1850, 1760, 2210, 2420, 2340, 2690, 2880, 2750, 3120,
    3010, 3380, 3540, 3430, 3710, 3890, 3780, 4010, 4170, 4050,
    4290, 4460, 4380, 4620, 4510, 4780, 4950, 4830, 5120, 5280,
  ],
  "90": [1240, 1520, 1710, 1660, 1930, 2280, 2450, 2720, 2680, 3010, 3240, 3520, 3760, 4010, 4290, 4510, 4780, 5030],
  "180": [920, 1120, 1350, 1610, 1580, 1870, 2110, 2360, 2610, 2870, 3090, 3370, 3620, 3890, 4170, 4460, 4780, 5120],
};
